version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
#      - ./.tmp/:/var/run/postgresql
    ports:
      - "5432:5432"

  web:
    container_name: web
    build: .
    env_file:
      - .env
    command: wait-for-it -t 60 db:5432 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - "./src/:/app"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
